//! Privacy projection for read-only family displays.
//!
//! Provider records and email content are deliberately absent from the public
//! output types. Network serving and pairing are separate, later gates.

use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};
use std::collections::BTreeMap;
use thiserror::Error;
use zeroize::{Zeroize, Zeroizing};

use base64::{engine::general_purpose::URL_SAFE_NO_PAD, Engine as _};
use rand::Rng;

const MAX_DISPLAY_ID_BYTES: usize = 100;
const MAX_TITLE_CHARS: usize = 200;
const MAX_PROJECTED_ITEMS: usize = 100;
const PAIRING_TTL_SECONDS: i64 = 300;
const MAX_PAIRING_ATTEMPTS: u8 = 5;

#[derive(Clone, Copy, Debug, Deserialize, Serialize, PartialEq, Eq, PartialOrd, Ord)]
#[serde(rename_all = "snake_case")]
pub enum DisplayCategory {
    Work,
    Family,
    School,
    Creche,
    Kids,
    Personal,
    Home,
}

#[derive(Clone, Copy, Debug, Deserialize, Serialize, PartialEq, Eq)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum PrivacyProfile {
    PublicFamily,
    Private,
    WorkPrivate,
    Sensitive,
}

#[derive(Clone, Copy, Debug, Deserialize, Serialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum DisplayKind {
    Task,
    Appointment,
    Reminder,
    Notice,
}

#[derive(Clone, Copy, Debug, Deserialize, Serialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum DetailLevel {
    Full,
    Generic,
    Hidden,
}

#[derive(Clone, Copy, Debug, Deserialize, Serialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub struct CategoryPolicy {
    pub public_family: DetailLevel,
    pub private: DetailLevel,
    pub work_private: DetailLevel,
}

impl CategoryPolicy {
    pub const fn family_default() -> Self {
        Self {
            public_family: DetailLevel::Full,
            private: DetailLevel::Generic,
            work_private: DetailLevel::Hidden,
        }
    }

    pub const fn work_default() -> Self {
        Self {
            public_family: DetailLevel::Generic,
            private: DetailLevel::Hidden,
            work_private: DetailLevel::Hidden,
        }
    }
}

#[derive(Clone, Debug, Deserialize, Serialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct DisplayPolicy {
    pub categories: BTreeMap<DisplayCategory, CategoryPolicy>,
}

impl Default for DisplayPolicy {
    fn default() -> Self {
        let mut categories = BTreeMap::new();
        for category in [
            DisplayCategory::Family,
            DisplayCategory::School,
            DisplayCategory::Creche,
            DisplayCategory::Kids,
            DisplayCategory::Personal,
            DisplayCategory::Home,
        ] {
            categories.insert(category, CategoryPolicy::family_default());
        }
        categories.insert(DisplayCategory::Work, CategoryPolicy::work_default());
        Self { categories }
    }
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct ProjectionInput<'a> {
    /// Opaque display-safe identifier generated by the host projection layer.
    pub display_id: &'a str,
    pub title: &'a str,
    pub kind: DisplayKind,
    pub category: DisplayCategory,
    pub privacy: PrivacyProfile,
    pub starts_at: Option<&'a str>,
    pub ends_at: Option<&'a str>,
}

#[derive(Clone, Debug, Deserialize, Serialize, PartialEq, Eq)]
#[serde(deny_unknown_fields, rename_all = "camelCase")]
pub struct ProjectedDisplayItem {
    pub display_id: String,
    pub title: String,
    pub kind: DisplayKind,
    pub category: DisplayCategory,
    pub starts_at: Option<String>,
    pub ends_at: Option<String>,
    pub detail_level: DetailLevel,
}

#[derive(Clone, Copy, Debug, Deserialize, Serialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum DisplayMode {
    Today,
    Week,
    Month,
    Morning,
    Evening,
}

#[derive(Clone, Debug, Deserialize, Serialize, PartialEq, Eq)]
#[serde(deny_unknown_fields, rename_all = "camelCase")]
pub struct DisplaySnapshot {
    pub schema_version: u16,
    pub generated_at: String,
    pub mode: DisplayMode,
    pub items: Vec<ProjectedDisplayItem>,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum ProjectionOutcome {
    Visible,
    Hidden(HiddenReason),
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum HiddenReason {
    SensitiveProfile,
    CategoryPolicy,
}

#[derive(Debug, Error, PartialEq, Eq)]
pub enum ProjectionError {
    #[error("invalid display-safe identifier")]
    InvalidDisplayId,
    #[error("invalid display-safe title")]
    InvalidTitle,
    #[error("invalid display snapshot")]
    InvalidSnapshot,
}

pub fn build_snapshot(
    generated_at: &str,
    mode: DisplayMode,
    items: Vec<ProjectedDisplayItem>,
) -> Result<DisplaySnapshot, ProjectionError> {
    let snapshot = DisplaySnapshot {
        schema_version: 1,
        generated_at: generated_at.to_owned(),
        mode,
        items,
    };
    validate_snapshot(&snapshot)?;
    Ok(snapshot)
}

/// Revalidates an untrusted snapshot after deserialization on a display client.
pub fn validate_snapshot(snapshot: &DisplaySnapshot) -> Result<(), ProjectionError> {
    if snapshot.schema_version != 1
        || snapshot.items.len() > MAX_PROJECTED_ITEMS
        || !looks_like_rfc3339(&snapshot.generated_at)
    {
        return Err(ProjectionError::InvalidSnapshot);
    }
    for item in &snapshot.items {
        validate_identifier(&item.display_id)?;
        validate_title(&item.title)?;
        if item.detail_level == DetailLevel::Hidden
            || item
                .starts_at
                .as_deref()
                .is_some_and(|value| !looks_like_rfc3339(value))
            || item
                .ends_at
                .as_deref()
                .is_some_and(|value| !looks_like_rfc3339(value))
        {
            return Err(ProjectionError::InvalidSnapshot);
        }
    }
    Ok(())
}

fn looks_like_rfc3339(value: &str) -> bool {
    let bytes = value.as_bytes();
    (20..=40).contains(&bytes.len())
        && bytes.get(4) == Some(&b'-')
        && bytes.get(7) == Some(&b'-')
        && bytes.get(10) == Some(&b'T')
        && (value.ends_with('Z')
            || bytes
                .iter()
                .skip(19)
                .any(|byte| matches!(byte, b'+' | b'-')))
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct PairingChallenge {
    pub code: String,
    pub expires_at_unix: i64,
}

pub struct IssuedDisplayCredential {
    pub display_id: String,
    pub token: Zeroizing<String>,
    pub token_sha256: [u8; 32],
}

impl std::fmt::Debug for IssuedDisplayCredential {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter
            .debug_struct("IssuedDisplayCredential")
            .field("display_id", &self.display_id)
            .field("token", &"[REDACTED]")
            .field("token_sha256", &"[REDACTED]")
            .finish()
    }
}

#[derive(Debug, Error, PartialEq, Eq)]
pub enum PairingError {
    #[error("pairing is unavailable")]
    Unavailable,
    #[error("pairing confirmation was rejected")]
    Rejected,
}

#[derive(Default)]
pub struct PairingSession {
    pending: Option<PendingPairing>,
}

struct PendingPairing {
    code: [u8; 6],
    expires_at_unix: i64,
    failed_attempts: u8,
}

impl PairingSession {
    pub fn begin(&mut self, now_unix: i64) -> PairingChallenge {
        let mut rng = rand::rng();
        let value = rng.random_range(0..1_000_000_u32);
        let code_text = format!("{value:06}");
        let mut code = [0_u8; 6];
        code.copy_from_slice(code_text.as_bytes());
        let expires_at_unix = now_unix.saturating_add(PAIRING_TTL_SECONDS);
        self.pending = Some(PendingPairing {
            code,
            expires_at_unix,
            failed_attempts: 0,
        });
        PairingChallenge {
            code: code_text,
            expires_at_unix,
        }
    }

    pub fn confirm(
        &mut self,
        submitted_code: &str,
        now_unix: i64,
    ) -> Result<IssuedDisplayCredential, PairingError> {
        let Some(pending) = self.pending.as_mut() else {
            return Err(PairingError::Unavailable);
        };
        if now_unix > pending.expires_at_unix || pending.failed_attempts >= MAX_PAIRING_ATTEMPTS {
            pending.code.zeroize();
            self.pending = None;
            return Err(PairingError::Unavailable);
        }
        let submitted = submitted_code.as_bytes();
        let matches = submitted.len() == pending.code.len()
            && submitted
                .iter()
                .zip(pending.code.iter())
                .fold(0_u8, |difference, (left, right)| {
                    difference | (left ^ right)
                })
                == 0;
        if !matches {
            pending.failed_attempts = pending.failed_attempts.saturating_add(1);
            if pending.failed_attempts >= MAX_PAIRING_ATTEMPTS {
                pending.code.zeroize();
                self.pending = None;
            }
            return Err(PairingError::Rejected);
        }

        pending.code.zeroize();
        self.pending = None;
        let display_id = format!("display-{}", random_url_token(16));
        let token = Zeroizing::new(random_url_token(32));
        let token_sha256: [u8; 32] = Sha256::digest(token.as_bytes()).into();
        Ok(IssuedDisplayCredential {
            display_id,
            token,
            token_sha256,
        })
    }
}

fn random_url_token(bytes: usize) -> String {
    let mut value = vec![0_u8; bytes];
    rand::rng().fill(value.as_mut_slice());
    let encoded = URL_SAFE_NO_PAD.encode(&value);
    value.zeroize();
    encoded
}

pub fn project_item(
    policy: &DisplayPolicy,
    input: ProjectionInput<'_>,
) -> Result<(ProjectionOutcome, Option<ProjectedDisplayItem>), ProjectionError> {
    validate_identifier(input.display_id)?;
    validate_title(input.title)?;

    if input.privacy == PrivacyProfile::Sensitive {
        return Ok((
            ProjectionOutcome::Hidden(HiddenReason::SensitiveProfile),
            None,
        ));
    }

    let category_policy =
        policy
            .categories
            .get(&input.category)
            .copied()
            .unwrap_or(CategoryPolicy {
                public_family: DetailLevel::Hidden,
                private: DetailLevel::Hidden,
                work_private: DetailLevel::Hidden,
            });
    let requested = match input.privacy {
        PrivacyProfile::PublicFamily => category_policy.public_family,
        PrivacyProfile::Private => category_policy.private,
        PrivacyProfile::WorkPrivate => category_policy.work_private,
        PrivacyProfile::Sensitive => unreachable!(),
    };
    // Private and work-private details can never become full text on a shared
    // display, even if a malformed or future policy requests it.
    let level = match (input.privacy, requested) {
        (PrivacyProfile::Private | PrivacyProfile::WorkPrivate, DetailLevel::Full) => {
            DetailLevel::Generic
        }
        _ => requested,
    };
    if level == DetailLevel::Hidden {
        return Ok((
            ProjectionOutcome::Hidden(HiddenReason::CategoryPolicy),
            None,
        ));
    }

    let title = if level == DetailLevel::Full {
        input.title.to_owned()
    } else {
        generic_title(input.kind).to_owned()
    };
    Ok((
        ProjectionOutcome::Visible,
        Some(ProjectedDisplayItem {
            display_id: input.display_id.to_owned(),
            title,
            kind: input.kind,
            category: input.category,
            starts_at: input.starts_at.map(str::to_owned),
            ends_at: input.ends_at.map(str::to_owned),
            detail_level: level,
        }),
    ))
}

fn generic_title(kind: DisplayKind) -> &'static str {
    match kind {
        DisplayKind::Task | DisplayKind::Reminder => "Reminder",
        DisplayKind::Appointment => "Appointment",
        DisplayKind::Notice => "Family notice",
    }
}

fn validate_identifier(value: &str) -> Result<(), ProjectionError> {
    if value.len() < 16
        || value.len() > MAX_DISPLAY_ID_BYTES
        || !value
            .bytes()
            .all(|byte| byte.is_ascii_alphanumeric() || matches!(byte, b'-' | b'_'))
    {
        return Err(ProjectionError::InvalidDisplayId);
    }
    Ok(())
}

fn validate_title(value: &str) -> Result<(), ProjectionError> {
    let trimmed = value.trim();
    if trimmed.is_empty()
        || trimmed.chars().count() > MAX_TITLE_CHARS
        || trimmed.chars().any(char::is_control)
    {
        return Err(ProjectionError::InvalidTitle);
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn input(privacy: PrivacyProfile, category: DisplayCategory) -> ProjectionInput<'static> {
        ProjectionInput {
            display_id: "display-item-0001",
            title: "Confidential clinic review",
            kind: DisplayKind::Appointment,
            category,
            privacy,
            starts_at: Some("2026-09-01T16:30:00+01:00"),
            ends_at: Some("2026-09-01T17:00:00+01:00"),
        }
    }

    #[test]
    fn public_family_items_keep_display_safe_details() {
        let (_, projected) = project_item(
            &DisplayPolicy::default(),
            input(PrivacyProfile::PublicFamily, DisplayCategory::Family),
        )
        .unwrap();
        let projected = projected.unwrap();
        assert_eq!(projected.title, "Confidential clinic review");
        assert_eq!(projected.detail_level, DetailLevel::Full);
    }

    #[test]
    fn private_items_are_generic_and_sensitive_items_never_project() {
        let (_, private) = project_item(
            &DisplayPolicy::default(),
            input(PrivacyProfile::Private, DisplayCategory::Family),
        )
        .unwrap();
        assert_eq!(private.unwrap().title, "Appointment");

        let (outcome, sensitive) = project_item(
            &DisplayPolicy::default(),
            input(PrivacyProfile::Sensitive, DisplayCategory::Family),
        )
        .unwrap();
        assert_eq!(
            outcome,
            ProjectionOutcome::Hidden(HiddenReason::SensitiveProfile)
        );
        assert!(sensitive.is_none());
    }

    #[test]
    fn work_private_is_hidden_by_default_and_full_override_is_capped() {
        let (_, hidden) = project_item(
            &DisplayPolicy::default(),
            input(PrivacyProfile::WorkPrivate, DisplayCategory::Work),
        )
        .unwrap();
        assert!(hidden.is_none());

        let mut policy = DisplayPolicy::default();
        policy.categories.insert(
            DisplayCategory::Work,
            CategoryPolicy {
                work_private: DetailLevel::Full,
                ..CategoryPolicy::work_default()
            },
        );
        let (_, capped) = project_item(
            &policy,
            input(PrivacyProfile::WorkPrivate, DisplayCategory::Work),
        )
        .unwrap();
        let capped = capped.unwrap();
        assert_eq!(capped.detail_level, DetailLevel::Generic);
        assert_eq!(capped.title, "Appointment");
    }

    #[test]
    fn output_schema_has_no_provider_or_email_fields() {
        let (_, projected) = project_item(
            &DisplayPolicy::default(),
            input(PrivacyProfile::PublicFamily, DisplayCategory::Family),
        )
        .unwrap();
        let json = serde_json::to_string(&projected.unwrap()).unwrap();
        for forbidden in [
            "provider", "account", "email", "subject", "sender", "body", "source",
        ] {
            assert!(!json.to_ascii_lowercase().contains(forbidden));
        }
    }

    #[test]
    fn pairing_is_short_lived_single_use_and_returns_a_redacted_secret() {
        let mut session = PairingSession::default();
        let challenge = session.begin(1_000);
        assert_eq!(challenge.code.len(), 6);
        assert!(challenge.code.bytes().all(|byte| byte.is_ascii_digit()));
        assert_eq!(challenge.expires_at_unix, 1_300);

        let credential = session.confirm(&challenge.code, 1_100).unwrap();
        assert!(credential.display_id.starts_with("display-"));
        assert_eq!(credential.token.len(), 43);
        assert_eq!(
            credential.token_sha256,
            <[u8; 32]>::from(Sha256::digest(credential.token.as_bytes()))
        );
        let debug = format!("{credential:?}");
        assert!(!debug.contains(credential.token.as_str()));
        assert!(matches!(
            session.confirm(&challenge.code, 1_101),
            Err(PairingError::Unavailable)
        ));
    }

    #[test]
    fn pairing_expires_and_locks_after_bounded_failures() {
        let mut expired = PairingSession::default();
        let challenge = expired.begin(2_000);
        assert!(matches!(
            expired.confirm(&challenge.code, 2_301),
            Err(PairingError::Unavailable)
        ));

        let mut limited = PairingSession::default();
        limited.begin(3_000);
        for _ in 0..MAX_PAIRING_ATTEMPTS {
            assert!(matches!(
                limited.confirm("000000x", 3_001),
                Err(PairingError::Rejected)
            ));
        }
        assert!(matches!(
            limited.confirm("000000", 3_002),
            Err(PairingError::Unavailable)
        ));
    }

    #[test]
    fn snapshot_contract_is_versioned_bounded_and_read_only() {
        let (_, item) = project_item(
            &DisplayPolicy::default(),
            input(PrivacyProfile::PublicFamily, DisplayCategory::Family),
        )
        .unwrap();
        let snapshot = build_snapshot(
            "2026-09-01T09:00:00+01:00",
            DisplayMode::Morning,
            vec![item.unwrap()],
        )
        .unwrap();
        assert_eq!(snapshot.schema_version, 1);
        let json = serde_json::to_string(&snapshot).unwrap();
        for forbidden in ["action", "command", "complete", "acknowledge", "url"] {
            assert!(!json.to_ascii_lowercase().contains(forbidden));
        }

        let item = snapshot.items[0].clone();
        assert_eq!(
            build_snapshot(
                "2026-09-01T09:00:00+01:00",
                DisplayMode::Today,
                vec![item; MAX_PROJECTED_ITEMS + 1],
            ),
            Err(ProjectionError::InvalidSnapshot)
        );
        assert_eq!(
            build_snapshot("not-a-time", DisplayMode::Today, vec![]),
            Err(ProjectionError::InvalidSnapshot)
        );

        let mut hidden = snapshot.clone();
        hidden.items[0].detail_level = DetailLevel::Hidden;
        assert_eq!(
            validate_snapshot(&hidden),
            Err(ProjectionError::InvalidSnapshot)
        );

        let unknown = r#"{"schemaVersion":1,"generatedAt":"2026-09-01T09:00:00Z","mode":"today","items":[],"provider":"forbidden"}"#;
        assert!(serde_json::from_str::<DisplaySnapshot>(unknown).is_err());
    }
}
