#include <dlfcn.h>
#include <stddef.h>
#include <stdint.h>
#include <string.h>
#include <stdlib.h>
#include "llama.h"

// Sizes were generated by compiling the official b10434 llama.h at commit
// 7e4c0a968 on arm64 macOS. See LLAMA_ABI.md for source digests.
enum {
    PA_LLAMA_MODEL_PARAMS_SIZE = 72,
    PA_LLAMA_CONTEXT_PARAMS_SIZE = 160,
    PA_LLAMA_SAMPLER_CHAIN_PARAMS_SIZE = 1,
    PA_LLAMA_BATCH_SIZE = 56,
};

_Static_assert(PA_LLAMA_MODEL_PARAMS_SIZE == 72, "unexpected model ABI");
_Static_assert(PA_LLAMA_CONTEXT_PARAMS_SIZE == 160, "unexpected context ABI");
_Static_assert(PA_LLAMA_SAMPLER_CHAIN_PARAMS_SIZE == 1, "unexpected sampler ABI");
_Static_assert(PA_LLAMA_BATCH_SIZE == 56, "unexpected batch ABI");

static const char * const PA_REQUIRED_SYMBOLS[] = {
    "llama_backend_init",
    "llama_backend_free",
    "llama_model_default_params",
    "llama_context_default_params",
    "llama_sampler_chain_default_params",
    "llama_model_load_from_file",
    "llama_model_free",
    "llama_model_get_vocab",
    "llama_model_chat_template",
    "llama_chat_apply_template",
    "llama_init_from_model",
    "llama_free",
    "llama_tokenize",
    "llama_token_to_piece",
    "llama_batch_get_one",
    "llama_decode",
    "llama_sampler_chain_init",
    "llama_sampler_chain_add",
    "llama_sampler_init_grammar",
    "llama_sampler_init_greedy",
    "llama_sampler_sample",
    "llama_sampler_accept",
    "llama_sampler_free",
    "llama_vocab_is_eog",
    "llama_log_set",
};

// Returns 0 only when the exact API surface required by the persistent backend
// is exported. It never loads a model or emits library errors to application IPC.
int32_t pa_llama_probe_library(const char * path) {
    if (path == NULL || path[0] == '\0') {
        return 1;
    }
    void * handle = dlopen(path, RTLD_LOCAL | RTLD_NOW);
    if (handle == NULL) {
        return 2;
    }
    const size_t symbol_count = sizeof(PA_REQUIRED_SYMBOLS) / sizeof(PA_REQUIRED_SYMBOLS[0]);
    for (size_t index = 0; index < symbol_count; index++) {
        if (dlsym(handle, PA_REQUIRED_SYMBOLS[index]) == NULL) {
            dlclose(handle);
            return 3;
        }
    }
    dlclose(handle);
    return 0;
}

typedef struct llama_model_params pa_model_params;
typedef struct llama_context_params pa_context_params;
typedef struct llama_batch pa_batch;
typedef struct llama_sampler_chain_params pa_chain_params;

_Static_assert(sizeof(pa_model_params) == PA_LLAMA_MODEL_PARAMS_SIZE, "model params layout");
_Static_assert(sizeof(pa_context_params) == PA_LLAMA_CONTEXT_PARAMS_SIZE, "context params layout");
_Static_assert(sizeof(pa_chain_params) == PA_LLAMA_SAMPLER_CHAIN_PARAMS_SIZE, "chain params layout");
_Static_assert(sizeof(pa_batch) == PA_LLAMA_BATCH_SIZE, "batch layout");

typedef pa_model_params (*pa_model_default_fn)(void);
typedef pa_context_params (*pa_context_default_fn)(void);
typedef pa_chain_params (*pa_chain_default_fn)(void);
typedef void (*pa_void_fn)(void);
typedef void * (*pa_model_load_fn)(const char *, pa_model_params);
typedef void (*pa_ptr_free_fn)(void *);
typedef const void * (*pa_vocab_fn)(const void *);
typedef const char * (*pa_model_chat_template_fn)(const void *, const char *);
typedef int32_t (*pa_chat_apply_template_fn)(const char *, const struct llama_chat_message *, size_t, _Bool, char *, int32_t);
typedef void * (*pa_context_init_fn)(void *, pa_context_params);
typedef int32_t (*pa_tokenize_fn)(const void *, const char *, int32_t, int32_t *, int32_t, _Bool, _Bool);
typedef pa_batch (*pa_batch_one_fn)(int32_t *, int32_t);
typedef int32_t (*pa_decode_fn)(void *, pa_batch);
typedef void * (*pa_chain_init_fn)(pa_chain_params);
typedef void (*pa_chain_add_fn)(void *, void *);
typedef void * (*pa_grammar_fn)(const void *, const char *, const char *);
typedef void * (*pa_greedy_fn)(void);
typedef int32_t (*pa_sample_fn)(void *, void *, int32_t);
typedef void (*pa_accept_fn)(void *, int32_t);
typedef _Bool (*pa_eog_fn)(const void *, int32_t);
typedef int32_t (*pa_piece_fn)(const void *, int32_t, char *, int32_t, int32_t, _Bool);
typedef void (*pa_load_backends_fn)(const char *);
typedef ggml_backend_dev_t (*pa_device_by_type_fn)(enum ggml_backend_dev_type);
typedef void (*pa_log_callback)(int, const char *, void *);
typedef void (*pa_log_set_fn)(pa_log_callback, void *);

static void pa_discard_log(int level, const char * text, void * user_data) {
    (void) level; (void) text; (void) user_data;
}

typedef struct {
    void * library;
    void * model;
    const void * vocab;
    pa_model_chat_template_fn model_chat_template;
    pa_chat_apply_template_fn chat_apply_template;
    pa_context_default_fn context_default;
    pa_chain_default_fn chain_default;
    pa_context_init_fn context_init;
    pa_ptr_free_fn context_free;
    pa_tokenize_fn tokenize;
    pa_batch_one_fn batch_one;
    pa_decode_fn decode;
    pa_chain_init_fn chain_init;
    pa_chain_add_fn chain_add;
    pa_grammar_fn grammar;
    pa_greedy_fn greedy;
    pa_sample_fn sample;
    pa_accept_fn accept;
    pa_ptr_free_fn sampler_free;
    pa_eog_fn is_eog;
    pa_piece_fn token_piece;
    pa_ptr_free_fn model_free;
    pa_void_fn backend_free;
    int32_t gpu_layers;
    ggml_backend_dev_t * devices;
} pa_backend;

#define PA_SYM(handle, name, type) ((type) dlsym((handle), (name)))

void * pa_llama_backend_open(const char * library_path, const char * runtime_dir,
                             const char * model_path, int32_t gpu_layers) {
    if (!library_path || !runtime_dir || !model_path) return NULL;
    void * library = dlopen(library_path, RTLD_LOCAL | RTLD_NOW);
    if (!library) return NULL;
    pa_load_backends_fn load_backends = PA_SYM(library, "ggml_backend_load_all_from_path", pa_load_backends_fn);
    pa_void_fn backend_init = PA_SYM(library, "llama_backend_init", pa_void_fn);
    pa_model_default_fn model_default = PA_SYM(library, "llama_model_default_params", pa_model_default_fn);
    pa_model_load_fn model_load = PA_SYM(library, "llama_model_load_from_file", pa_model_load_fn);
    pa_log_set_fn log_set = PA_SYM(library, "llama_log_set", pa_log_set_fn);
    if (!load_backends || !backend_init || !model_default || !model_load || !log_set) { dlclose(library); return NULL; }
    if (getenv("PA_LLAMA_DEBUG") == NULL) log_set(pa_discard_log, NULL);
    load_backends(runtime_dir);
    backend_init();
    pa_model_params params = model_default();
    params.n_gpu_layers = gpu_layers;
    ggml_backend_dev_t * cpu_devices = NULL;
    if (gpu_layers == 0) {
        pa_device_by_type_fn device_by_type = PA_SYM(library, "ggml_backend_dev_by_type", pa_device_by_type_fn);
        if (!device_by_type) { PA_SYM(library, "llama_backend_free", pa_void_fn)(); dlclose(library); return NULL; }
        cpu_devices = calloc(2, sizeof(*cpu_devices));
        if (!cpu_devices) { PA_SYM(library, "llama_backend_free", pa_void_fn)(); dlclose(library); return NULL; }
        cpu_devices[0] = device_by_type(GGML_BACKEND_DEVICE_TYPE_CPU);
        if (!cpu_devices[0]) { free(cpu_devices); PA_SYM(library, "llama_backend_free", pa_void_fn)(); dlclose(library); return NULL; }
        params.devices = cpu_devices;
    }
    void * model = model_load(model_path, params);
    if (!model) { free(cpu_devices); PA_SYM(library, "llama_backend_free", pa_void_fn)(); dlclose(library); return NULL; }
    pa_backend * state = calloc(1, sizeof(*state));
    if (!state) { PA_SYM(library, "llama_model_free", pa_ptr_free_fn)(model); free(cpu_devices); PA_SYM(library, "llama_backend_free", pa_void_fn)(); dlclose(library); return NULL; }
    state->library = library; state->model = model;
    state->gpu_layers = gpu_layers;
    state->devices = cpu_devices;
    state->vocab = PA_SYM(library, "llama_model_get_vocab", pa_vocab_fn)(model);
    state->model_chat_template = PA_SYM(library, "llama_model_chat_template", pa_model_chat_template_fn);
    state->chat_apply_template = PA_SYM(library, "llama_chat_apply_template", pa_chat_apply_template_fn);
    state->context_default = PA_SYM(library, "llama_context_default_params", pa_context_default_fn);
    state->chain_default = PA_SYM(library, "llama_sampler_chain_default_params", pa_chain_default_fn);
    state->context_init = PA_SYM(library, "llama_init_from_model", pa_context_init_fn);
    state->context_free = PA_SYM(library, "llama_free", pa_ptr_free_fn);
    state->tokenize = PA_SYM(library, "llama_tokenize", pa_tokenize_fn);
    state->batch_one = PA_SYM(library, "llama_batch_get_one", pa_batch_one_fn);
    state->decode = PA_SYM(library, "llama_decode", pa_decode_fn);
    state->chain_init = PA_SYM(library, "llama_sampler_chain_init", pa_chain_init_fn);
    state->chain_add = PA_SYM(library, "llama_sampler_chain_add", pa_chain_add_fn);
    state->grammar = PA_SYM(library, "llama_sampler_init_grammar", pa_grammar_fn);
    state->greedy = PA_SYM(library, "llama_sampler_init_greedy", pa_greedy_fn);
    state->sample = PA_SYM(library, "llama_sampler_sample", pa_sample_fn);
    state->accept = PA_SYM(library, "llama_sampler_accept", pa_accept_fn);
    state->sampler_free = PA_SYM(library, "llama_sampler_free", pa_ptr_free_fn);
    state->is_eog = PA_SYM(library, "llama_vocab_is_eog", pa_eog_fn);
    state->token_piece = PA_SYM(library, "llama_token_to_piece", pa_piece_fn);
    state->model_free = PA_SYM(library, "llama_model_free", pa_ptr_free_fn);
    state->backend_free = PA_SYM(library, "llama_backend_free", pa_void_fn);
    if (!state->vocab || !state->model_chat_template || !state->chat_apply_template ||
        !state->context_default || !state->chain_default || !state->context_init ||
        !state->context_free || !state->tokenize || !state->batch_one || !state->decode ||
        !state->chain_init || !state->chain_add || !state->grammar || !state->greedy ||
        !state->sample || !state->accept || !state->sampler_free || !state->is_eog ||
        !state->token_piece || !state->model_free || !state->backend_free) {
        state->model_free(model); free(state->devices); state->backend_free(); dlclose(library); free(state); return NULL;
    }
    return state;
}

int32_t pa_llama_backend_generate(void * opaque, const char * prompt, const char * grammar,
                                  int32_t max_tokens, char * output, size_t output_cap) {
    pa_backend * state = opaque;
    if (!state || !prompt || !grammar || !output || output_cap < 2 || max_tokens < 1 || max_tokens > 512) return 1;
    const char * chat_template = state->model_chat_template(state->model, NULL);
    if (!chat_template) return 2;
    struct llama_chat_message message = { "user", prompt };
    size_t formatted_cap = strlen(prompt) * 3 + 1024;
    if (formatted_cap > INT32_MAX) return 2;
    char * formatted = malloc(formatted_cap);
    if (!formatted) return 3;
    int32_t prompt_len = state->chat_apply_template(chat_template, &message, 1, 1, formatted, (int32_t) formatted_cap);
    if (prompt_len < 1) { free(formatted); return 2; }
    if ((size_t) prompt_len >= formatted_cap) {
        formatted_cap = (size_t) prompt_len + 1;
        char * resized = realloc(formatted, formatted_cap);
        if (!resized) { free(formatted); return 3; }
        formatted = resized;
        prompt_len = state->chat_apply_template(chat_template, &message, 1, 1, formatted, (int32_t) formatted_cap);
        if (prompt_len < 1 || (size_t) prompt_len >= formatted_cap) { free(formatted); return 2; }
    }
    int32_t token_count = -state->tokenize(state->vocab, formatted, prompt_len, NULL, 0, 1, 1);
    if (token_count <= 0 || token_count > 3584) { free(formatted); return 2; }
    int32_t * tokens = malloc((size_t) token_count * sizeof(*tokens));
    if (!tokens) { free(formatted); return 3; }
    if (state->tokenize(state->vocab, formatted, prompt_len, tokens, token_count, 1, 1) < 0) { free(formatted); free(tokens); return 2; }
    free(formatted);
    pa_context_params params = state->context_default();
    params.n_ctx = 4096;
    params.n_batch = (uint32_t) token_count;
    // A zero-layer configuration is the explicit no-Metal fallback used when
    // command queues are unavailable (including restricted test runners).
    if (state->gpu_layers == 0) {
        params.offload_kqv = 0;
        params.op_offload = 0;
    }
    void * context = state->context_init(state->model, params);
    if (!context) { free(tokens); return 4; }
    void * sampler = state->chain_init(state->chain_default());
    void * grammar_sampler = state->grammar(state->vocab, grammar, "root");
    void * greedy = state->greedy();
    if (!sampler || !grammar_sampler || !greedy) { if (sampler) state->sampler_free(sampler); state->context_free(context); free(tokens); return 5; }
    state->chain_add(sampler, grammar_sampler); state->chain_add(sampler, greedy);
    pa_batch batch = state->batch_one(tokens, token_count);
    size_t used = 0;
    for (int32_t generated = 0; generated < max_tokens; generated++) {
        if (state->decode(context, batch) != 0) { state->sampler_free(sampler); state->context_free(context); free(tokens); return 6; }
        int32_t token = state->sample(sampler, context, -1);
        if (state->is_eog(state->vocab, token)) break;
        char piece[512];
        int32_t piece_len = state->token_piece(state->vocab, token, piece, sizeof(piece), 0, 1);
        if (piece_len < 0 || used + (size_t) piece_len >= output_cap) { state->sampler_free(sampler); state->context_free(context); free(tokens); return 7; }
        memcpy(output + used, piece, (size_t) piece_len); used += (size_t) piece_len;
        tokens[0] = token; batch = state->batch_one(tokens, 1);
    }
    output[used] = '\0';
    state->sampler_free(sampler); state->context_free(context); free(tokens);
    return 0;
}

void pa_llama_backend_close(void * opaque) {
    pa_backend * state = opaque;
    if (!state) return;
    state->model_free(state->model); free(state->devices); state->backend_free(); dlclose(state->library); free(state);
}
